services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  pracadyplomowa:
    build: ./pracadyplomowa
    ports:
      - "5001:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__IdentityConnection=Host=postgres;Port=5432;Database=identity;Username=root;Password=root
    restart: always

  frontend-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "6000:80"
    depends_on:
      - pracadyplomowa
    environment:
      - VITE_BACKEND_URL=http://localhost:5001
    restart: always

volumes:
  postgres-data:
